LotoWebApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [path("admin/", admin.site.urls), path("", include("lottery.urls"))]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

lottery/urls.py
from django.urls import path
from lottery import views
import django.contrib.auth.views as authViews
app_name = "lottery"

urlpatterns = [
    path("", views.landing, name="landing"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("loterias/", views.lotteries, name="lotteries"),
    path("loterias/<str:name>/", views.lottery_detail, name="lottery-detail"),
    path("loterias/<str:name>/concursos/<int:number>", views.draw_detail, name="draw-detail"),
    path("jogos", views.games, name="games"),
    path("jogos/conjuntos/<int:game_set_id>", views.game_set_detail, name="game-set-detail"),
    path("jogos/colecoes/<int:collection_id>", views.collection_detail, name="collection-detail"),
    path("jogos/colecoes/criar-colecao", views.create_collection, name="create-collection"),
    path("jogos/geradores", views.games_generators, name="generators"),
    path("editar-conjuntos", views.edit_games_sets, name="edit-games-sets"),
    path("enviar-conjuntos", views.send_game_sets, name="send-games-sets"),
    path("exportar-conjuntos", views.export_games_sets, name="export-games-sets"),
    path("editar-colecoes", views.edit_collections, name="edit-collections"),
    path("enviar-colecoes/", views.send_collections, name="send-collections"),
    path("exportar-colecoes", views.export_collections, name="export-collections"),
    path("resultados", views.results_reports, name="results"),
    path("resultados/<int:result_id>", views.results_reports_detail, name="result-detail"),
    path("resultados/<int:result_id>/exportar-jogos", views.export_results_reports_games, name="export-results-reports-games"),
    path("resultados/<int:result_id>/criar-conjunto", views.create_game_set_from_result, name="create_game_set_from_result"),
    path("deletar-resultados/<int:result_id>", views.delete_results_reports, name="delete-results-reports"),
    path("enviar-resultados/<int:result_id>", views.send_results_reports, name="send-results-reports"),
    path("exportar-resultados", views.export_results_reports, name="export-results-reports"),
    path("profile", views.profile, name="profile"),
    path("login", views.CustomLoginView.as_view(), name="login"),
    path("logout", views.CustomLogoutView.as_view(), name="logout"),
    path("cadastro", views.register, name="register"),
    path("billing", views.billing, name="billing"),
    path("get-draws/<str:name>", views.get_draws_numbers, name="get-draws"),
    path("create-results-report", views.create_results_report, name="create-results-report"),
    path("get-combinations", views.get_combinations, name="get-combinations"),
    path("save-games-batch", views.save_games_batch, name="save-games-batch")

]

templates/platform/dashboard/base.html
<!--
=========================================================
* Soft UI Dashboard - v1.0.3
=========================================================

* Product Page: https://www.creative-tim.com/product/soft-ui-dashboard
* Copyright 2021 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Loto Assistant</title>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
  <title>
    Soft UI Dashboard by Creative Tim
  </title>
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet"/>
  <!-- Nucleo Icons -->
  <link href="{% static 'assets/css/nucleo-icons.css' %}" rel="stylesheet"/>
  <link href="{% static 'assets/css/nucleo-svg.css' %}" rel="stylesheet"/>
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <link href="{% static 'assets/css/nucleo-svg.css' %}" rel="stylesheet"/>
  <!-- CSS Files -->
  <link id="pagestyle" href="{% static 'assets/css/soft-ui-dashboard.css' %}" rel="stylesheet"/>
  <link href="{% static 'css/main.css' %}" rel="stylesheet"/>
  <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap5.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/select/1.3.4/css/select.dataTables.min.css"/>
  {% block css %}
  {% endblock %}


</head>

<style>

</style>
<body class="g-sidenav-show">
{% if messages %}
<ul class="messages d-none" id="messages">
  {% for message in messages %}
  <li class="{{message.tags}}">{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}
<!-- Sidebar -->
{% include 'components/sidebar.html' %}
<!-- End Sidebar -->
<main class="main-content position-relative mt-1 border-radius-lg " style="min-height:100vh;">

  <!-- Navbar -->
  {% include 'components/navbar.html' %}
  <!-- End Navbar -->

  <!-- Content -->
  {% block content %}

  {% endblock %}
  <!-- End Content -->

  <!-- Footer -->
  {% include 'components/footer.html' %}
  <!-- End Footer -->
</main>
</body>
</html>

<!--   Core JS Files   -->
<script src="{% static 'assets/js/core/popper.min.js' %}"></script>
<script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/perfect-scrollbar.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/smooth-scrollbar.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/chartjs.min.js' %}"></script>
<script async defer src="https://buttons.github.io/buttons.js"></script>
<script src="{% static 'assets/js/soft-ui-dashboard.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
  var pathname = window.location.pathname
  var links = document.getElementsByClassName('nav-link')
  for(link of links){
    if(link.id && pathname.includes(link.id)){
      link.classList.add('active')
    }
  }

  var breadcrumb = document.getElementById('breadcrumb')
  var pathnameList = pathname.split('/').filter(value => value != '')
  console.log(pathnameList)
  breadcrumb.innerHTML += `<li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="">Plataforma</a></li>`
  for(name of pathnameList){
    breadcrumb.innerHTML += `<li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="${name}">${name}</a></li>`
  }
  breadcrumb.lastChild = `<li class="breadcrumb-item text-sm text-dark active" aria-current="page">${name}</li>`
  document.getElementById('currentPage').innerHTML = name.substring(0, 1).toUpperCase() + name.substring(1)


</script>

<script src="{% static 'js/aux.js' %}"></script>
<script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap5.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/select/1.3.4/js/dataTables.select.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjs/9.5.1/math.js"></script>
{% block script %}
{% endblock %}

templates/platform/dashboard/lotteries.html
<!--
=========================================================
* Soft UI Dashboard - v1.0.3
=========================================================

* Product Page: https://www.creative-tim.com/product/soft-ui-dashboard
* Copyright 2021 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->

{% extends 'platform/dashboard/base.html' %}
{% load static %}
{% load numbers %}
{% block content %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap5.min.css">

<div class="container-fluid py-4">
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      {% for draw in lastDraws %}
      {% with 'assets/img/loterias/logos/'|add:draw.lottery_name|add:'.png' as lotteryLogo %}
      {% if forloop.counter == 1 %}
      <div class="carousel-item active">
      {% else %}
       <div class="carousel-item">
      {% endif %}
        <div class="card w-90 m-auto">
          <div class="card-body p-3">
            <div class="col">
              <div class="d-flex flex-row justify-content-evenly align-items-center">
                <img src="{% static lotteryLogo %}" alt="Logo da {{draw.loto_name}}"
                         class="btn-tooltip text-info text-gradient" data-bs-toggle="tooltip"
                         data-bs-placement="top"
                         title="Logo da {{draw.loto_name}}" data-container="body" data-animation="true">
                <span class="text-sm mb-0 text-capitalize font-weight-bold mr-3">
                  Concurso {{draw.number}} - {{draw.date|date:"d/m/Y"}}
                </span>
                <div class="numbers d-inline">
                  {% for number in draw.result %}
                  <span class="badge badge-sm bg-gradient-primary">
                    {{number}}
                  </span>
                  {% endfor %}
                </div>
                <a href="{% url 'lottery:draw-detail' draw.lottery_name draw.number %}">
                    <span class="btn-inner--icon"><i class="fa fa-info-circle" style="font-size:20px"></i></span>
                  </a>
              </div>

            </div>
          </div>
        </div>
      </div>
      {% endwith %}
      {% endfor %}
    </div>
    <button class="carousel-control-prev mx-0" style='opacity:1; width:auto;' type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon"  aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" style='opacity:1; width:auto;' data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <div class="row mx-1 my-1 mt-4">
    <div class="col-lg-13 mb-lg-0 mb-4">
      <div class="card h-100">
        <div class="card-body p-3">
          <div class="row">
            <div class="col-lg-4">
              <div class="d-flex flex-column h-100">
                <h5 class="font-weight-bolder">Histórico dos Concursos</h5>
                <p class="mb-2">Confira todos os concursos de cada loteria e filtre por números sorteados, premiação e acumulado.
                </p>
                <a class="text-body text-sm font-weight-bold mb-0 icon-move-right mt-auto" href="javascript:;">
                  Leia sobre
                  <i class="fas fa-arrow-right text-sm ms-1" aria-hidden="true"></i>
                </a>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="px-2">
                <img src="{% static 'assets/img/lottery-page1.svg' %}"
                     class="w-100 position-relative z-index-2 pt-4" alt="waves">
              </div>
            </div>
            <div class="col-lg-4">
              <div class="d-flex flex-column h-100">
                <h5 class="font-weight-bolder">Análises Estatísticas</h5>
                <p class="mb-2">Confira o ranking de números, quais combinações saem juntas e veja quantitativos matemáticos
                  sobre cada concurso.
                </p>
                <a class="text-body text-sm font-weight-bold mb-0 icon-move-right mt-auto" href="javascript:;">
                  Leia sobre
                  <i class="fas fa-arrow-right text-sm ms-1" aria-hidden="true"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    <div class="row mx-1 my-1">
    <div class="col-lg-5 my-3">
      <div class="card h-100">
        <div class="card-body p-3">
          <div class="row">
            <div class="col">
              <div class="d-flex flex-column h-100">
                <h5 class="font-weight-bolder">Loterias Disponíveis</h5>
                <p class="text-body">Nossa plataforma suporta as seguintes modalidades da Loteria Federal.</p>
                <div class="d-flex flex-row w-100 p-3">
                  {% for lottery in lotteries %}
                  <img src="{% static 'assets/img/loterias/logos/'|add:lottery.name|add:'.png' %}" alt="Logo da {{lottery.name|capfirst}}"
                       class="btn-tooltip mx-3" data-bs-toggle="tooltip" data-bs-placement="top"
                       title="{{ lottery.name }}" data-container="body" data-animation="true"
                       style="width:50px; height:50px;">
                  {% endfor %}
                </div>
                <a class="text-body text-sm font-weight-bold mb-0 icon-move-right mt-auto" href="javascript:;">
                  Leia sobre
                  <i class="fas fa-arrow-right text-sm ms-1" aria-hidden="true"></i>
                </a>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-7 mb-lg-0 my-3">
      <div class="card h-100">
        <div class="overflow-hidden position-relative border-radius-lg bg-cover h-100">
          <div class="card-body position-relative z-index-1 d-flex flex-column h-100 p-3">
            <h5 class="font-weight-bolder">Página da Loteria</h5>
           <p class="text-body">Escolha a loteria desejada e clique no botão para ser redirecionado.</p>
            <div class="d-flex flex-column w-100">
                  <h6 class="font-weight-bolder">Modalidades</h6>
                <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
                  {% for lottery in lotteries %}
                  <input type="radio" class="btn-check" name="select-lottery" id="modalidade-{{lottery.name}}"
                         value="{% url 'lottery:lottery-detail' lottery.name %}"
                         autocomplete="off" required>
                  <label class="btn btn-outline-primary" for="modalidade-{{lottery.name}}">{{lottery.name}}</label>
                  {% endfor %}
                </div>
                <input type="button" class="btn btn-primary mt-2 text-align disabled" id="redirect" onclick="redirect()" value="VER PÁGINA"
                style="width:150px; margin:auto;">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</div>


{% endblock %}

{% block script %}
<script>
    $(document).ready(function() {
    $('#drawsTable').DataTable({
      language: {
            "lengthMenu": "Mostrar _MENU_ jogos por página",
            "zeroRecords": "",
            "info": "Página _PAGE_ de _PAGES_",
            "infoEmpty": "Nenhum jogo encontrado",
            "infoFiltered": "(Filtrados de _MAX_ jogos)",
            "paginate": {
              "previous": "←",
              "next": "→"
            },
            "searchPlaceholder": "Busque jogos por loteria, nome ou status",
            "search": "Filtrar"

        }
    });

    $('#collectionsTable_filter input[type="search"]').attr(
      'placeholder', "Busque por loteria, nome ou nº de jogos"
    )

    $('.dataTables_filter input[type="search"]').css(
     {'width':'300px','display':'inline-block'}
  );
} );


</script>
<script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }

$("input[name='select-lottery']").change(function(){
  var isChecked = $("input[name='select-lottery']:checked").val()
  console.log(isChecked)
  if( !isChecked ){
    $("#redirect").addClass("disabled")
  }
  else{
    $("#redirect").removeClass("disabled")
  }
})
function redirect(){
  window.location.href = $("input[name='select-lottery']:checked").val()

}
</script>
<script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap5.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjs/9.5.1/math.js"></script>
{% endblock %}